### ISSUE TITLE
Insets unable to work with NavigationPage

### ISSUE THREAD

**Issue by 1357310795** [the49code/The49.Maui.Insets#1]
## Description
Set a NavigationPage as the root page, Insets fails to work. 

## Steps to Reproduce
1. Clone and open the solution
2. In App.xaml.cs, replace `MainPage = new AppShell();` with `MainPage = new NavigationPage(new MainPage());`
3. Run the sample

## Problem
After debugging, I found that `navigationPage.NavigatedTo` was not fired when navigate to a new ContentPage (use navigationPage.PushAsync();). I'm not sure whether it's a bug of MAUI or not.

![image](https://user-images.githubusercontent.com/35869804/214745271-d11df83f-1599-419a-8d6e-4e0bd741b526.png)

**Comment by paulvarache** [comment]
Good catch. I suspect `NavigatedTo` is the event inherited by the base `Page` class so it doesn't fire as the page doesn't technically get navigated to, being the root page. I'll have to look into it and find a workaround to get notified of a page change
